# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 17:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gcdissue',
            name='alt_large_url',
        ),
        migrations.RemoveField(
            model_name='gcdissue',
            name='alt_medium_url',
        ),
        migrations.RemoveField(
            model_name='gcdissue',
            name='alt_small_url',
        ),
        migrations.RemoveField(
            model_name='gcdissue',
            name='large_url',
        ),
        migrations.RemoveField(
            model_name='gcdissue',
            name='medium_url',
        ),
        migrations.RemoveField(
            model_name='gcdissue',
            name='small_url',
        ),
        migrations.RemoveField(
            model_name='gcdseries',
            name='cover_url',
        ),
        migrations.AddField(
            model_name='gcdissue',
            name='alt_large_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover/issue'),
        ),
        migrations.AddField(
            model_name='gcdissue',
            name='alt_medium_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover/issue'),
        ),
        migrations.AddField(
            model_name='gcdissue',
            name='alt_small_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover/issue'),
        ),
        migrations.AddField(
            model_name='gcdissue',
            name='large_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover/issue'),
        ),
        migrations.AddField(
            model_name='gcdissue',
            name='medium_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover/issue'),
        ),
        migrations.AddField(
            model_name='gcdissue',
            name='small_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover/issue'),
        ),
        migrations.AddField(
            model_name='gcdseries',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='cover/series'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='cgc_rating',
            field=models.FloatField(blank=True, choices=[(10.0, '10.0 Gem Mint'), (9.9, '9.9 Mint'), (9.8, '9.8 Near Mint/Mint'), (9.6, '9.6 Near Mint +'), (9.4, '9.4 Near Mint'), (9.2, '9.2 Near Mint -'), (9.0, '9.0 Very Fine/Near Mint'), (8.5, '8.5 Very Fine +'), (8.0, '8.0 Very Fine'), (7.5, '7.5 Very Fine -'), (7.0, '7.0 Fine/Very Fine'), (6.5, '6.5 Fine +'), (6.0, '6.0 Fine'), (5.5, '5.5 Fine -'), (5.0, '5.0 Very Good/Fine'), (4.5, '4.5 Very Good +'), (4.0, '4.0 Very Good'), (3.5, '3.5 Very Good -'), (3.0, '3.0 Good/Very Good'), (2.5, '2.5 Good +'), (2.0, '2.0 Good'), (1.8, '1.8 Good -'), (1.5, '1.5 Fair/Good'), (1.0, '1.0 Fair'), (0.5, '.5 Poor'), (0, 'NG')], null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='comic',
            name='label_colour',
            field=models.CharField(blank=True, choices=[('Yellow', 'CGC Yellow Label'), ('Blue', 'CGC Blue Label'), ('Purple', 'CGC Purple Label'), ('Red', 'CGC Red Label'), ('cbcs', 'CBCS'), ('pgx', 'PGX')], max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='currency',
            field=models.PositiveSmallIntegerField(choices=[(124, 'CAD'), (840, 'USD'), (484, 'MXN')], default=124),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.PositiveSmallIntegerField(choices=[(124, 'CAD'), (840, 'USD'), (484, 'MXN')], default=124),
        ),
        migrations.AlterField(
            model_name='store',
            name='currency',
            field=models.PositiveSmallIntegerField(choices=[(124, 'CAD'), (840, 'USD'), (484, 'MXN')], default=124),
        ),
    ]
